travis:
  secure:
    BINSTAR_TOKEN: j9mM+GzPp/KLtWJfL48oi6FwdF3WTTK1vxHAhfmOhi8UHTMoekqt8TulO14q481L1I6GrqK5VGvGiDor/Na50Ng/pMm1y9IFCl/X5w7+0TOrBtCCXVkPQQJp5AMOltNuyOJ/mroBBkAnvXw67frLjsJTQGMZ4etVb7cDXT8KJGMhA1ca+MO0G3eBLM/bKro7e4Z+JB7x1qzWgibO4sgf0enuMBJP+Osl2TDIIQB1kIlvWRsuDKJ5ReFKoCySzlBlt4+yFSeexZmPcYYmG6yVAZKtW4+Ij4TEd845an+n/BTPEqkAh4iYxB5OPRASqAaU2Lt7ljWCA295ypguvbHdMfSRXivWCTOIwWuF3iGA2F0cGyfLK1lltPkKwyDLyXv1bEl9nsP6sz3sTW1Zip8vo7LtohA5hwH3eVF62epDm6vGCpMkdVh38bg5LXjf8tD8JvwWek8yuT9R42uUtkwK6ogmhvUXT82/HFplQUKmVt33L7f8wvikH3vo3ZcM4oyH+qkhCW3rW7YPNn2xWk345JXizqvxxVGOjqyDeA4zG5O9TErt8wBjdR/sM1Gx9LTMO6e1hq8i0NYHzx+COK/qSCHEZugEiuY3OfsMweZ5ja/TPTszuzer7r6hoDfpJ8Wfo4jubxWa+0HYoxtoxSBC5Ku/abvsK6KCeKqzstKhqBw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
