travis:
  secure:
    BINSTAR_TOKEN: mlf9zXljEXsndWXAuUlmuWDH+aGA8K0f1Nrm1iy57gFW6HHVS6/FXOIVTzm8OPwtE2unh71D3u9VpsiIlMOeFYQtPGGubDHVtqKZx1zMCHDac6Q+TfVsky10+JsUeJI3DVI33aMwK9Oe9fCitzJTQnT5QEco46RPDK/cH28+w2e4N46rAGS8gJySPOUQP+aW2ELphlXuoR5Trc5JOdvnMw/SGBAsfi+gog/F6J58f8s3tju5ZRBGskotM/2t4+auPjs/2MPa54ZehtMeLcbCFmpaOZ/OJEdU4gzMStlTelS/8pBTL6c/Im0pho0corOkA/MQLj/fV92SPdhdfMyDTZejubHzw93SEiJbrB1AOPK8Fh2WR5sTztk45OhgghfOawRftG6nEinS587HyfXthtfGck8yVd/fyRK90KMs7g3kB+kTkPvDcbURmBT01ELpXCV5a8sSJrIlMJ13ceDY9i5SSfvg3eyAUDyNB6HEUDTnMzpn5b0nYbEwDMS433OlPeSYxcV0ncRbX0Rm35RKnaJjt9zun+qNC9cLAz2tJxwLQoXdDL9ijjFvSZimW/C7Tr0X4dyZ6PnWVEfk/8sxox3fZ/Re1qSTHwQ94LvlcX1rWMms5qW+sTSoaeaM2FRDQb14GmPuc1rMZRmdqHFENQ0Txwy7i3kvTo0uPr+kmW4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
